import{a as $,S as E,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",S="48208907-81157ac097d3685843fe42362";async function h(t,o=1,s=15){const n=`${v}?key=${S}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${s}`,{data:e}=await $.get(n);if(e.hits.length===0)throw new Error("No images found");return e}function y(t){return t.map(({webformatURL:o,largeImageURL:s,tags:n,likes:e,views:r,comments:l,downloads:b})=>`
        <a class="gallery-item" href="${s}">
          <img src="${o}" alt="${n}" loading="lazy"/>
          <div class="info">
            <p><span>Likes</span><span>${e}</span></p>
            <p><span>Views</span><span>${r}</span></p>
            <p><span>Comments</span><span>${l}</span></p>
            <p><span>Downloads</span><span>${b}</span></p>
          </div>
        </a>`).join("")}const R=document.querySelector("#search-form"),c=document.querySelector(".gallery"),q=document.querySelector(".loader"),u=document.createElement("button");u.textContent="Load More";u.classList.add("load-more-btn","is-hidden");c.insertAdjacentElement("afterend",u);let L=new E(".gallery a"),p="",g=1,f=0,d=0;const w=15;function H(){c.innerHTML="",d=0}function m(t){u.classList.toggle("is-hidden",!t)}function i(t){q.style.display=t?"block":"none"}R.addEventListener("submit",async t=>{if(t.preventDefault(),p=t.target.elements.searchQuery.value.trim(),!p){a.warning({title:"Warning",message:"Enter a search term!",position:"topRight",timeout:3e3});return}g=1,H(),m(!1),i(!0);try{const{hits:o,totalHits:s}=await h(p,g,w);if(f=s,i(!1),f===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,class:"custom-toast"});return}c.insertAdjacentHTML("beforeend",y(o)),L.refresh(),d=o.length,a.success({title:"Success",message:`Found ${s} images!`,position:"topRight",timeout:3e3}),m(d<f)}catch{i(!1),a.error({title:"Error",message:"Something went wrong!",position:"topRight",timeout:3e3})}});u.addEventListener("click",async()=>{g+=1,i(!0);try{const{hits:t}=await h(p,g,w);i(!1),c.insertAdjacentHTML("beforeend",y(t)),L.refresh(),d+=t.length;const{height:o}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),d>=f&&(m(!1),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}))}catch{i(!1),a.error({title:"Error",message:"Failed to load more images!",position:"topRight",timeout:3e3})}});
//# sourceMappingURL=index.js.map
