import{S as m,i}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d="https://pixabay.com/api/",g="48208907-81157ac097d3685843fe42362";async function y(o,r=1,n=12){const s=`${d}?key=${g}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`,e=await fetch(s);if(!e.ok)throw new Error("Failed to fetch images");return e.json()}function h(o){return o.map(({webformatURL:r,largeImageURL:n,tags:s,likes:e,views:t,comments:a,downloads:f})=>`
          <a class="gallery-item" href="${n}" data-title="${s}">
            <img src="${r}" alt="${s}" loading="lazy"/>
            <div class="info">
              <p><span>Likes</span><span>${e}</span></p>
              <p><span>Views</span><span>${t}</span></p>
              <p><span>Comments</span><span>${a}</span></p>
              <p><span>Downloads</span><span>${f}</span></p>
            </div>
          </a>`).join("")}const $=document.querySelector("#search-form"),u=document.querySelector(".gallery"),L=document.querySelector(".loader");let w=new m(".gallery a"),c="",p=1;function S(){u.innerHTML=""}function l(o){L.style.display=o?"block":"none"}$.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){i.warning({title:"Warning",message:"Enter a search term!",position:"topRight",timeout:3e3});return}p=1,S(),l(!0);try{const{hits:r,totalHits:n}=await y(c,p);if(l(!1),r.length===0){i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,class:"custom-toast"});return}u.insertAdjacentHTML("beforeend",h(r)),w.refresh(),i.success({title:"Success",message:`Found ${n} images!`,position:"topRight",timeout:3e3})}catch{l(!1),i.error({title:"Error",message:"Something went wrong!",position:"topRight",timeout:3e3})}});
//# sourceMappingURL=index.js.map
